hak5/bashbunny-payloads

- payloads/library/DuckyTemplate/ducky_script.txt
- payloads/library/DuckyTemplate/payload.txt
- payloads/library/DuckyTemplate/readme.txt
Simple boiler plate for ducky scripts. Just modify the ducky_script.txt file with duck code and put this package in any switch position
> Add Boilerplate for Ducky Scripts

- payloads/library/ExecutableInstaller/payload.txt
I didn't know you'd merge them all in one swoop so it wasn't ready. My bad for creating a PR before it was done :)
> Add bunny_helpers.sh to ExecutableInstaller

- payloads/library/WiPassDump/a.cmd
- payloads/library/WiPassDump/payload.txt
- payloads/library/WiPassDump/readme.md
Runs powershell as Administrator, bypasses UAC and dumps cleartext Wi-Fi passwords and infos to the Bash Bunny.
> WiPassDump

- payloads/library/MacReverseShell/payload.txt
- payloads/library/MacReverseShell/readme.md
Reverse Shell for mac users. also added the DYLD exploit
> Mac Reverse Shell

- payloads/library/GitBunnyGit/README.md
- payloads/library/GitBunnyGit/payload.txt
This payload was made in collaboration with audibleblink through irc. We both came up with the same idea, but I took it a step further, by adding a git-pull/update after the first payload execution. Original repo at https://github.com/mathew-fleisch/Git-Bunny-Git
> Payload to automatically set up/update git repo

- payloads/library/GitBunnyGit/README.md
- payloads/library/GitBunnyGit/payload.txt
This payload should assume that bunny_helper.sh doesn't exist yet, so it cannot be sourced. I removed that part of the code, and the variable it was being used for. I also updated the read-me documentation to remove an old error state.
> Fixed a bug and updated the read-me doc.

- payloads/library/smb_exfiltrator/payload.txt
- payloads/library/smb_exfiltrator/readme.md
This is an awesome payload check out Hak5 episode 2202
> Add SMB Exfiltrator Payload

- payloads/library/smb_exfiltrator/payload.txt
Modified -WindowStyle to be hidden instead of minimized
> Modified smb_exfil to be more hidden

- .gitignore
- payloads/library/Captiveportal/portal.html
"username" is not a valid value for the type attribute in an input tag, which causes it to fail formal validation.  Probably would never*really* affect anything, but...you know...
> Change username input tag's type attribute from "username" to "text"

- payloads/library/Powershell_TCP_Extractor/copyMoveData.ps1
- payloads/library/Powershell_TCP_Extractor/d.cmd
- payloads/library/Powershell_TCP_Extractor/payload.txt
- payloads/library/Powershell_TCP_Extractor/readme.md
tested on win10... lmk what you think
> payload that leverages powershell to extract data via tcp

- payloads/library/BruteBunny/brutebunny.ps1
- payloads/library/BruteBunny/passwords.txt
- payloads/library/BruteBunny/payload.txt
- payloads/library/BruteBunny/readme.md
- payloads/library/BruteBunny/usernames.txt
- payloads/library/ProcessInfo/payload.txt
- payloads/library/ProcessInfo/readme.md
Hey Hak5, these are some of the payloads I've been working on. BruteBunny and Process Info. Let me know if you have questions or concerns!
Decoy
> Decoy's Payloads

- payloads/library/Notepad Fun/payload.txt
> Funny Notepad Prank

- payloads/library/BlackBackup/credentials.ps1
- payloads/library/BlackBackup/payload.txt
BlackBackup is a Powershell (and thus Windows) backup script that is easy to configure. Make quick backups of files, the registry, passwords, WiFi Keys, SAM database etc. and save them to the BashBunny. This is a HID + STORAGE attack. Now, let's eat some carrots!
> BlackBackup

- payloads/library/android_open_url/README.md
- payloads/library/android_open_url/payload.txt
This payload opens a URL on the default browser on an unlocked android... quickly.
> Android Open URL

- payloads/library/psh_DownloadExec/payload.txt
- payloads/library/psh_DownloadExec/psh.txt
- payloads/library/psh_DownloadExec/readme.md
Simple Windows Powershell payload to download a Powershell script from the BashBunny and run on the target machine. No internet access required.
> [PAYLOAD] psh_DownloadExec

- payloads/library/LinuxReverseShell/README.md
- payloads/library/LinuxReverseShell/a.sh
- payloads/library/LinuxReverseShell/payload.txt
Doing a clean Pull request as the last one has some tag-a-long changes as well :-)
> LinuxReverseShell Payload

- payloads/library/InfoGrabber/info.ps1
- payloads/library/InfoGrabber/payload.txt
- payloads/library/InfoGrabber/readme.md
- payloads/library/InfoGrabber/run.ps1
I have made a payload that uses powershell scripts to get information about a windows computer and save it in a text file. It will also show the saved wifi passwords. This payload is usefull if you want to gather information automaticly, which is perfect for computer maintainers at companies and so on. 
At the moment the output file gets a 01234 which I am trying to remove, but not sure how.
> InfoGrabber - Version 2.0

- payloads/library/ftp_exfiltrator/1.ps1
- payloads/library/ftp_exfiltrator/payload.txt
- payloads/library/ftp_exfiltrator/readme.md
> New Payload - FTP Exfiltration

- payloads/library/WifiGrabber/ducky_script.txt
- payloads/library/WifiGrabber/payload.txt
- payloads/library/WifiGrabber/readme.md
- payloads/library/WindowsMeterpreterStaged/payload.txt
- payloads/library/WindowsMeterpreterStaged/readme.md
- payloads/library/WindowsMeterpreterStaged/sc.txt
- payloads/library/WindowsMeterpreterStaged/windows-staged-meterpreter.txt
I've added two payloads that I've created myself and made great use of and enjoyed using for the past 2 weeks since I got my bash bunny. I'd love to share these with the community and hope that they'll be taken and greatly improved upon. Also excuse my awful powershell scripting. I'm a bash person not a windows powershell/cmd person. So I had much fun learning too in developing these payloads and hopefully will receive good feedback to improve and learn more. Thanks! :)
> meterpreter staged payload and wifi grabber payloads

- payloads/library/PasswordGrabber/d.cmd
- payloads/library/PasswordGrabber/e.cmd
- payloads/library/PasswordGrabber/i.vbs
- payloads/library/PasswordGrabber/payload.txt
- payloads/library/PasswordGrabber/readme.md
> PasswordGrabber

- payloads/library/SmacAndGrab/payload.txt
More loot from https://github.com/Seekurity/BrowserCookieGrabber/blob/master/browserCookieGrabber.sh
> More loot :)

- payloads/library/InfiniteControl/payload.txt
- payloads/library/InfiniteControl/readme.md
Hit the CONTROL key every 10 seconds in an infinite loop, while blinking
the red LED with every keypress.
> Initial release of InfiniteControl

- payloads/library/remote_access/LinuxReverseShell/README.md
- payloads/library/remote_access/LinuxReverseShell/payload.txt
The following changed were made:
- Updated LED's to match the new standard ones
- Removed `source bunny_helpers.sh`
- Changed `LANGUAGE='us'` to `DUCKY_LANG us`
> LinuxReverseShell v1.1 - Update to BashBunny v1.1

- payloads/library/prank/Notepad_fun/payload.txt
> Fixed typo

- payloads/library/exfiltration/smb_exfiltrator/payload.txt
Wait for port 445 (SMB) rather than ICMP Ping response
This is a recreation of https://github.com/hak5/bashbunny-payloads/pull/154 per @sebkinne
> SMB_Exfiltrator: PowerShell improvements

- payloads/library/general/DuckyTemplate/payload.txt
- payloads/library/general/DuckyTemplate/readme.md
Updated version number.
Updated LED status table.
> Updated Ducky Template for firmware version 1.1

- payloads/library/execution/psh_DownloadExecSMB/payload.txt
- payloads/library/execution/psh_DownloadExecSMB/psh.txt
- payloads/library/execution/psh_DownloadExecSMB/readme.md
Localized SMB Powershell delivery. For when USB and Web methods are disabled or too noisy.
> [PAYLOAD/EXECUTION] psh_DownloadExecSMB - Powershell SMB Delivery

- payloads/library/credentials/MrRobot/payload.txt
Hey all, this pull request will fix a stabilities issues like time delay, new updates from fw 1.1 and colors thats more clearly between state changes.
> Fix stabilities issues, and implemented to fw 1.1

- payloads/library/exfiltration/MacPDFExfil/payload.txt
- payloads/library/recon/MacProfiler/payload.txt
- payloads/library/recon/MacProfiler/readme.md
added sub folder so all files are not in root of loot folder
> New Payload MacProfiler

- payloads/library/exfiltration/browserData/payload.txt
Fixed the payload for 1.0 but if you want it ported for 1.1, change line 38 to (LED M)
> Fixed for 1.0 and 1.1

- payloads/library/execution/RAZ_VBScript/a.vbs
- payloads/library/execution/RAZ_VBScript/payload.txt
- payloads/library/execution/RAZ_VBScript/readme.md
- payloads/library/prank/RAZ_ThemeChanger/payload.txt
- payloads/library/prank/RAZ_ThemeChanger/readme.md
> Minor updates

- payloads/library/execution/StickyBunny/payload.txt
- payloads/library/execution/StickyBunny/readme.md
Not sure what the protocol is for submitting a pull request here, let me know if there is anything that I would need to do on my end.
> added stickyBunny payload

- payloads/library/prank/macDesktop/README.md
- payloads/library/prank/macDesktop/macWallpaper.sh
- payloads/library/prank/macDesktop/payload.txt
Runs a script in background that will download pictures of my little pony (or whatever else you'd like, just change the urls to the pictures) and randomly sets that as their desktop background every 45 minutes - 5 hours. You can change number in for loop to decide how many times it will change their background.
https://forums.hak5.org/topic/41605-payload-macwallpaper/
> Add macDesktop prank

- payloads/library/general/Windows NIC Sharing/p.ps1
- payloads/library/general/Windows NIC Sharing/payload.txt
- payloads/library/general/Windows NIC Sharing/readme.md
- payloads/library/general/Windows NIC Sharing/server.py
Bash Bunny payload for setting up Internet Sharing with Windows 10
> Windows NIC Sharing

- payloads/library/general/InfiniteControl/payload.txt
Changed LED colors, added BREAK.
> New version InfiniteControl

- payloads/extensions/get.sh
Wouldn't it be better to give TARGET_OS a value other than always exporting it as 'UNKNOWN'
> actually giving TARGET_OS a value

- payloads/library/recon/InfoGrabber/info.ps1
- payloads/library/recon/InfoGrabber/payload.txt
- payloads/library/recon/InfoGrabber/readme.md
Updated the InfoGrabber payload.
It now uses the newer extensions, executes faster and executes in a more discrete manner (hidden powershell windows).
Also cleaned up the code and removed unneeded code (including an unneeded, and less reliable, repeat of getting the WiFi passwords)and commented the code.
> InfoGrabber Version 2.0

- payloads/library/prank/Startup-Message/payload.txt
- payloads/library/prank/Startup-Message/readme.md
This little HID Attack will use cmd to create a file in the startup directory of the logged in user on the target PC, which will display a message set by the attacker on logging in.
> Added Startup-Message

- payloads/library/prank/win93/payload.txt
* removed usage of fixed browsers 
* added execution of the default browser
* shortened browser calls
> win93 prank: added use of default browser / removed static browsers

- payloads/library/credentials/bushingsBlueTurtle/blueTurtle.py
- payloads/library/credentials/bushingsBlueTurtle/payload.txt
- payloads/library/credentials/bushingsBlueTurtle/post.sh
- payloads/library/credentials/bushingsBlueTurtle/pre.sh
- payloads/library/credentials/bushingsBlueTurtle/readme.md
- payloads/library/credentials/bushingsBlueTurtle/shell.py
- payloads/library/credentials/bushingsBlueTurtle/shellSmuggler.py
This payload is kind of scary.  Repeatedly dropped root shells on both mac and linux system.  Has means for evading antivirus.  Wasn't entirely sure I wanted to make this thing public.
Essentially this will wrap sudo and store the password.  It seems to be pretty silent in its running.  After running the sudo command, it will fire off a reverse https meterpreter session using sudo for a root shell.  It will do this every time the user runs something with sudo.  Seemed to not even give itself away when running more interactive things through the wrapper like trying to vim a file.
Dedicated to Bushing and Kerbs.
> Bushings blue turtle

- payloads/library/remote_access/LinuxReverseShell/README.md
- payloads/library/remote_access/LinuxReverseShell/a.sh
- payloads/library/remote_access/LinuxReverseShell/payload.txt
- Version 1.2
- Removed the need for Netcat to be installed
- Removed an unnecessary delay
> Update to LinuxReverseShell

- payloads/library/recon/LinuxInfoGrabber/README.md
- payloads/library/recon/LinuxInfoGrabber/payload.txt
- payloads/library/recon/LinuxInfoGrabber/recon.sh
Created Info Grabber for Linux
> Added Info Grabber for Linux

- payloads/library/poc/LINUX_HID/README.md
- payloads/library/poc/LINUX_HID/payload.txt
- payloads/library/poc/README.md
I created a EICAR style test file to simplify protection technology testing without blowing up the system by accident
> Proof-of-concept added: EICAR of bash bunny HID simulation for Linux

- languages/de.json
added umlauts and some other chars for german keyboard-layout.
added : ß,€,§,ö,ä,ü,Ö,Ä,Ü
> Added German umlauts

- payloads/library/general/InfiniteControl/payload.txt
Added logic to add support for a random interval pause between key presses _or_ having a fixed value each time.
> Update payload.txt for InfiniteControl

- payloads/library/prank/ncage/osx.txt
- payloads/library/prank/ncage/payload.txt
- payloads/library/prank/ncage/readme.md
- payloads/library/prank/ncage/win.txt
New payload. Determines host OS and installs a specified Chrome Extension. 
Default extension turns all images into Nicholas Cage. 
- uses new AUTOETHERNET attackmode
- uses new GET TARGET_OS functionality
- uses new DEBUG function
- uses new MAC_HAPPY extension
> [PAYLOAD] Universal Chrome Extension Installer

- payloads/extensions/get.sh
Scans more verbosely allowing us to gather more info from nmap.
> Update GET TARGET_OS so it works with AUTO_ETHERNET

- payloads/extensions/mac_happy.sh
Add fixes to make things more efficient.
> Update mac_happy.sh to version 0.3

- payloads/library/credentials/Roaster/invoke-kerberoast.ps1
- payloads/library/credentials/Roaster/payload.txt
- payloads/library/credentials/Roaster/readme.md
- payloads/library/credentials/Roaster/s.ps1
Uses Bash Bunny Ethernet+HID to run Kerberoast, then exports results via SMB to the loot directory.
> Kerberoast for the Bash Bunny

- payloads/library/credentials/Jackalope/readme.md
Received some feedback concerning the documentation for my payload, these changes reflect those clarifications.
> Clarying documentation based on user feedback.

- payloads/library/remote_access/RAZ_ReverseShell/payload.ps1
- payloads/library/remote_access/RAZ_ReverseShell/payload.txt
- payloads/library/remote_access/RAZ_ReverseShell/readme.md
- Clean up traces
- Bugfixes on newer firmware
- Improved documentation
- Fake hardware identifier
- Added persistence via autostart
- Disconnect on end
> Updated RaZ_ReverseShell

- payloads/library/prank/NiceShutdown/README.md
- payloads/library/prank/NiceShutdown/payload.txt
Hi. This is my first ever payload "NiceShutdown".
It shuts down a Windows mashine with the given message.
However, it is not tested yet.
I would love someone to test it, and have it merged into the official repository.
[Forum thread](https://forums.hak5.org/topic/50271-payload-tester-needed-niceshutdown-shutdown-payload/?tab=comments#comment-324760)
[The payload itself](https://github.com/Emilius123/emilius123-bashbunny-payloads/tree/master/payloads/library/prank/NiceShutdown)
> Add NiceShutdown

- payloads/library/prank/hide-startbar/payload.txt
- payloads/library/prank/hide-startbar/readme.md
Added a payload to pranks that uses Powershell the hide the Windows Startbar
> Add hide-startbar payload

- payloads/library/prank/WIN_powershell_ProgressBar-and-Popup/payload.txt
- payloads/library/prank/WIN_powershell_ProgressBar-and-Popup/readme.md
- payloads/library/prank/hide-startbar/payload.txt
- payloads/library/prank/hide-startbar/readme.md
Progress bar and Popup - Uses Power Shell to show a progress bar telling the user it's installing a virus. After that uses text-to-speech, then shows a few silly error messages.
> Add new prank payload

- payloads/library/exfiltration/WIN_PoSH_HKU_RegBackUp/payload.txt
- payloads/library/exfiltration/WIN_PoSH_HKU_RegBackUp/readme.md
- payloads/library/exfiltration/WIN_PoSH_SaveSecurityHive/payload.txt
- payloads/library/exfiltration/WIN_PoSH_SaveSecurityHive/readme.md
- payloads/library/prank/WIN_powershell_ProgressBar-and-Popup/payload.txt
- payloads/library/prank/WIN_powershell_ProgressBar-and-Popup/readme.md
- payloads/library/prank/hide-startbar/payload.txt
- payloads/library/prank/hide-startbar/readme.md
Added new payload to exfiltration that saves the HKU registry entry to the bunny
> Added new payload WIN_PoSH_HKU_RegBackUp

- payloads/library/execution/ATNT/final_stage.ps1
- payloads/library/execution/ATNT/payload.txt
- payloads/library/execution/ATNT/stage2.ps1
- payloads/library/execution/ATNT/stage3.ps1
Uses Windows Ease of Access Assistive Technology (https://docs.microsoft.com/en-us/windows/win32/winauto/ease-of-access---assistive-technology-registration) 
to persistently run code with NT AUTHORITY\SYSTEM rights.
> New payload: ATNT; Ease of Access Assistive Technology

- payloads/library/poc/WIN_PoSH_MorseCode/readme.md
> Update - PoC Win_PoSH_MorseCode

- payloads/library/execution/Get-System/payload.ps1
- payloads/library/execution/Get-System/payload.txt
- payloads/library/execution/Get-System/psgetsys.ps1
Disable "PowerShell" logging
Check if current process have "Administrator" privilege
Check "SeDebugPrivilege" policy
Retrieves the processes belonging to the "SYSTEM" account
For each system PID, test to obtain the "SYSTEM" account via the parent process
> Execution - Get System

- payloads/library/execution/RazerSystemShell/README.md
- payloads/library/execution/RazerSystemShell/payload.txt
Exploit Razer USA HID driver installation to System authority PowerShell. 
This is heavily based on Tweet by @_MG_ on 22nd Aug 2021 but modified to work with BashBunny
> New Payload: Razer System Shell

- payloads/library/exfiltration/HiveNightmare/README.md
- payloads/library/exfiltration/HiveNightmare/payload.txt
- payloads/library/exfiltration/HiveNightmare/stage2.ps1
Leverages CVE-2021–36934 to get SAM/SYSTEM/SECURITY hives.
This time properly commented ;)
> New payload: HiveNightmare

- payloads/library/general/Bluetooth2/README.md
- payloads/library/general/Bluetooth2/payload.txt
This is Different from the normal WAIT_FOR_PRESENT as it does multiple triggers and depending on what one it finds will effect what script will run.
Note: this is more of a template to show some cool ways Bluetooth can be used in the Bash Bunny Mark II
I figured getting it out there would allow others to do something with it.
> Bluetooth2

- payloads/library/execution/Win_PoSH_SSHServer/payload.txt
- payloads/library/execution/Win_PoSH_SSHServer/readme.md
Installs and runs a SSH Server on Windows.
> New Payload - SSH Server

- payloads/library/exfiltration/Win_PoSH_ReadItOut/payload.txt
- payloads/library/exfiltration/Win_PoSH_ReadItOut/readme.md
Super subtle exfiltration method ;-) 
Gets the Microsoft Speech API (SAPI) to read out the content of text files in the my documents directory.
> New Payload - Read It Out

- payloads/library/prank/DesktopFlood/README.md
- payloads/library/prank/DesktopFlood/payload.txt
This doesn't change your wallpaper, it covers a desktop in ANY image of your choice.
Do you know someone that keeps forgetting to sign out of their computer? Well not anymore.
> Desktop flooder

- payloads/library/prank/DesktopFlood/payload.txt
I foolishly forgot to add a second backslash to $ImageName
> so it actually works

- payloads/library/credentials/win_problemstepsrecorder/README.md
- payloads/library/credentials/win_problemstepsrecorder/payload.ps1
- payloads/library/credentials/win_problemstepsrecorder/payload.txt
Abuse of "Windows Problem Steps Recorder" to spy on a user's activities.
> Add Win_ProblemStepsRecorder

- payloads/library/prank/Win_PoSh_HiThere/payload.txt
- payloads/library/prank/Win_PoSh_HiThere/readme.md
- payloads/library/prank/Win_PoSh_HiThere/s
Creates a hidden link file that override the ctrl+c functionality.
So, where the use press ctrl+c it lunches the first sign-in animation.
> New Payload - Hi There

- payloads/library/general/Win_PoSH_RandomVid/payload.txt
- payloads/library/general/Win_PoSH_RandomVid/readme.md
- payloads/library/general/Win_PoSH_RandomVid/s
Downloads a list of Hak5 vids from YouTube (about 15 in the rss feed). 
Then pick one at random, then opens it in the browser.
> New Payload - Random vid

- payloads/library/execution/ScreenGrab/README.md
- payloads/library/execution/ScreenGrab/screenGrab/payload.sh
- payloads/library/execution/ScreenGrab/screenGrab/shell
- payloads/library/execution/ScreenGrab/screenGrab/systemBus
- payloads/library/execution/ScreenGrab/switch1/payload.txt
- payloads/library/execution/ScreenGrab/switch2/payload.txt
screenGrab payload captures snap shots of target's screen periodically and store them into bunny.
> Uploading ScreenGrab

- payloads/library/exfiltration/Win_HID_BackupKeyManager/payload.txt
- payloads/library/exfiltration/Win_HID_BackupKeyManager/readme.md
Create a backup of the key manager log-on credentials for servers, websites and programs.
> New Payload - KeyManger Backup

- payloads/library/credentials/FireSnatcher/FireSnatcher.bat
- payloads/library/credentials/FireSnatcher/README.md
- payloads/library/credentials/FireSnatcher/payload.txt
Payload to copy Firefox Password Database and Wifi Creds
> New Payload- FireSnatcher

- payloads/library/exfiltration/Mac_Exfil/payload.txt
- payloads/library/exfiltration/Mac_Exfil/readme.md
Exfiltrates files from logged in users Documents and Desktop folders
> add my own exfil payload

- payloads/library/remote_access/linux_random-reverse-shell/README.md
- payloads/library/remote_access/linux_random-reverse-shell/payload.txt
- payloads/library/remote_access/linux_random-reverse-shell/random_reverse-shell.sh
- Title:         Random Reverse Shell
- Author:        TW-D
- Version:       1.0
- Target:        Linux
- Category:      Remote Access
1) Checks the availability of binaries on the system.
2) Builds a list of possible payloads.
3) Performs one at random.
> Linux Random Reverse Shell

- payloads/library/Incident_Response/MalwareBunny/README.md
- payloads/library/Incident_Response/MalwareBunny/install/binwalk.sh
- payloads/library/Incident_Response/MalwareBunny/install/capstone.sh
- payloads/library/Incident_Response/MalwareBunny/install/dshell.sh
- payloads/library/Incident_Response/MalwareBunny/install/featherduster.sh
- payloads/library/Incident_Response/MalwareBunny/install/peepdf.sh
- payloads/library/Incident_Response/MalwareBunny/install/punbup.sh
- payloads/library/Incident_Response/MalwareBunny/install/setup.sh
- payloads/library/Incident_Response/MalwareBunny/install/ssdeep.sh
- payloads/library/Incident_Response/MalwareBunny/install/viper.sh
- payloads/library/Incident_Response/MalwareBunny/install/wabt.sh
- payloads/library/Incident_Response/MalwareBunny/install/yara.sh
- payloads/library/Incident_Response/MalwareBunny/switch1/payload.txt
- payloads/library/Incident_Response/MalwareBunny/switch2/payload.txt
This pull request is to add a new payload for Incident_Responce category. 
MalwareBunny payload is designed to turn the Bash Bunny into a portable malware analysis platform and/or a malware repository. 
This payload consists of a set of installer scripts, tested to run on Bash Bunny. Users can install everything at once or pick-and-choose individual tools. 
The primary tool of this payload is viper framework, which allows to easily store and retrieve malware samples via a web interface.
> New IR Payload - MalwareBunny

- payloads/extensions/sewait.sh
Messed up my branches and mixed pull requests, so I closed #327 and opened this one...
> [EXTENSION] SEWAIT - social engineering wait - a small extension to DarrenKitchen's wait

- payloads/extensions/prompt.sh
PR #156 Cleanup
This is an extension to get a prompt on any OS.  Some of this is redundant with the RUN extension in place (this was written prior to that....), but this tool also allows you to pull up a terminal window on each OS.
@sebkinne if you feel this is too much like RUN, you can close this PR without a merge! Thanks!
> Cross platform command prompt extension

- payloads/extensions/run.sh
Just a small change but this will launch programs as admin.
Useful as you may need a admin powershell
> EXTENSION UPDATE - Windows run as admin

- payloads/library/credentials/NoDefenseAgainstLaZagne/payload.ps1
Updated payload.ps1 to work with LaZagne 2.4.6
> updated payload.ps1
