hak5/bashbunny-payloads

payloads/library/bunny_helpers.sh

Allows you to use $switchposition in payloads. Useful for building paths relative to payload/

bunny_helper switch position

---

payloads/library/usb_exfiltrator/d.cmd
payloads/library/usb_exfiltrator/e.cmd
payloads/library/usb_exfiltrator/install.sh
payloads/library/usb_exfiltrator/payload.txt
payloads/library/usb_exfiltrator/readme.md

Information is at #5.
Don't merge until #4 or similar is accepted.

Remove references to root directory for usb-exfiltrator payload

---

payloads/library/ExecutableInstaller/d.cmd
payloads/library/ExecutableInstaller/e.cmd
payloads/library/ExecutableInstaller/i.vbs
payloads/library/ExecutableInstaller/payload.txt
payloads/library/ExecutableInstaller/readme.md

This payload copies an executable or executable and a folder to a location (default %APPDATA%) and launches it with any parameters specified.
Don't merge until #4 or similar is accepted.

Add ExecutableInstaller payload

---

payloads/library/DuckyTemplate/payload.txt

Removed the extra notepad.exe at the end that was combined with 'fi', caused second if statement to fail.

Removed notepad.exe at the end

---

payloads/library/SmacAndGrab/payload.txt
payloads/library/SmacAndGrab/readme.md

This payload lets you define a list of files to backup.
It also accepts `find` and `grep` subshell commands as "filenames" to dynamically and conditionally copy files.

[PAYLOAD] Dynamic macOS file backups

---

payloads/library/macinfograbber/payload.txt
payloads/library/macinfograbber/readme.md

- fixes lootdir path
- dont capitalize var names that aren't exported
- indentation
- escape shell characters that are passed to QUACK
- account for variable copy times by joining cp and exit commands
- sync the disk

Fixes macinfograbber payload

---

payloads/library/SmacAndGrab/payload.txt
payloads/library/SmacAndGrab/readme.md

This PR annotates some code and changes the default volume name back to BashBunny. Turns out this is the default name when plugging in a fresh BB. Something I'd done made it previously  mount as `NO NAME`,

smacandgrab - adds comments and vid/pid

---

payloads/library/Captiveportal/payload.txt
payloads/library/tools_installer/install.sh

Within the hak5 forum https://forums.hak5.org/index.php?/topic/40237-install-tools/
there were several problems mentioned which are solved with this update:
1. No need to move instead of copying tools_to_install to the switch directory due to use of bunny_helpers.sh
2. Check if everything is copied works even when the user OS has added hidden files (removing hidden files before test)

Updated install.sh to solve problems mentioned in forum

---

.gitignore

When developing on a mac, lots of '.DS_Store' files appear in each directory. This ignore will stop them being tracked by git

Added .gitignore file to ignore default Mac OSX files

---

payloads/library/ShellExec/evil.sh
payloads/library/ShellExec/hook.js
payloads/library/ShellExec/index.html
payloads/library/ShellExec/payload.txt
payloads/library/ShellExec/readme.md

This payload serves malicious files over http and uses HID to make the target `curl` or `wget` them straight into `sh` without saving to disk. 
Malicious files can be anything, but since this payload is also a webserver, it can serve malicious pages and infect browsers with things like BeEF hooks. Sample included

[PAYLOAD] - ShellExec

---

payloads/library/fireytv/payload.txt
payloads/library/fireytv/readme.md

Added a payload to enable ADB and Unknown sources on an Amazon FireTV, then use ADB to install an APK containing a meterpreter shell.

Added a payload to enable ADB and Unknown sources on an Amazon FireTV, then use ADB to install an APK containing a meterpreter shell

---

payloads/library/SingleSecondShell/ducky_script.txt
payloads/library/SingleSecondShell/payload.txt
payloads/library/SingleSecondShell/readme.md

The <1 Second ReverseShell Payload is going to run blazing fast on the Bash Bunny, and cannot work on any other BadUSB devices, such as the USB Rubber Ducky that quick. That is obviously the reason this Payload is dedicated and specifically designed for the Bash Bunny. Plug in, and before you know it, you've got a shell. How awesome is that?

[Payload] SingleSecondShell

---

payloads/library/MacGetUsers/payload.txt
payloads/library/MacGetUsers/readme.md

Simple payload to list the users on a mac and store them into a file on the BashBunny

Added payload to list users available on the Mac

---

payloads/library/macinfograbber/payload.txt

There was a line break on line 30 where in reads Chrome cookies and moves to BashBunny mass storage. Removed line break.

Update payload.txt for macinfograbber - extra line break 

---

payloads/library/MacPhish/payload.txt
payloads/library/MacPhish/readme.md

… For OS X, uses spotlight to launch terminal, then uses osascript command to phish for the users password, then saves the phished password back to the bashbunny.

Adding the MacPhish payload

---

payloads/library/exfiltration/MacPDFExfil/README.md
payloads/library/exfiltration/MacPDFExfil/payload.txt

Finds PDFs located in the Mac users home directory and copies them over to the BashBunny Storage.

MacPDFExfil

---

library/extensions/setkb.sh

This extension will allow the overwriting of the default input keyboard layout to en-US for easier execution of some of the Quack commands.  Its an alternative means to use the Ducky scripts for cases where you know the target environment but do not have the capabilities to generate a [language].json file.

An extension to overwrite the default keyboard layout to en-US

---

payloads/extensions/setkb.sh

the existing `get-Culture | Select -ExpandProperty Name` in `SETKB DONE` returned en-GB by default,
changed to `Get-WinSystemLocale | Select -ExpandProperty Name` to restore to the System Locale set by the Windows User

Edited setkb.sh to restore to Windows System-Locale

---

payloads/library/recon/InfoGrabber/info.ps1

When no Internet connection is available the command runs into an error:
"The remote name could not be resolved: 'ipinfo.io'"
Fixed this with a try and catch block
The command also runs into an error when Internet Explorer was never started.
"Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the
UseBasicParsing parameter and try again"
Fixed this with the -UseBasicParsing parameter

Fixed errors in public IP address command

---

payloads/library/exploitation/Metasploit-Autopwn/auto_pwn.rc
payloads/library/exploitation/Metasploit-Autopwn/payload.txt
payloads/library/exploitation/Metasploit-Autopwn/readme.md

Runs Metasploit db_autopwn module against the whole dhcp clients connected to the Bash Bunny device exploiting locked and unlocked machines that running vulnerable OSes or services.

Metasploit Autopwn Bash Bunny Payload

---

payloads/library/execution/RevShellBack/README.md
payloads/library/execution/RevShellBack/payload.txt

This payload sets up a reverse shell in PowerShell on Windows. The Bash Bunny would then send commands to the PC over USB ethernet using netcat. This can either be ran as administrator or a normal user.

RevShellBack

---

payloads/library/recon/GetServicePerm/GetServicePerm.ps1
payloads/library/recon/GetServicePerm/payload.txt
payloads/library/recon/GetServicePerm/readme.md

When executed on a Windows host the payload gathers a list of permissions on executables used as a service.
This is useful when a service is executed with elevated privileges but the executable is modifiable by everyone.
When this senario exists a normal user can modify or replace that executable with anything useful and have it run with elevated privileges.

GetServicePerm - New suggested payload

---

payloads/library/general/BlueTeamPCAudit/1.ps1
payloads/library/general/BlueTeamPCAudit/payload.txt
payloads/library/general/BlueTeamPCAudit/readme.md

The PowerShell script changes the user's background to "background.bmp", this allows Blue team to remind users to lock their PCs.
The PowerShell script also sends an email to the Security Team with information about the users PC.
This allows the Security Team to keep a record of repeatable offenders.

BlueTeamPCAudit

---

payloads/library/exfiltration/simple-usb-extractor/e.cmd
payloads/library/exfiltration/simple-usb-extractor/i.vbs
payloads/library/exfiltration/simple-usb-extractor/payload.txt
payloads/library/exfiltration/simple-usb-extractor/readme.md
payloads/library/exfiltration/simple-usb-extractor/x.cmd
payloads/library/exfiltration/simple-usb-extractor/z.cmd

Creation of the simple-usb-exfiltration payload
This improves upon usb_exfiltration payload in a handful of ways:
1. It is fairly easier to understand for those who aren't scripting wizards.
2. It doesn't grab a billion nested folders when things are installed.
3. It shows how to add different locations and file types explicitly, with the addition of creating if statements for their folder's existence.
4. By default it looks for more file types in more locations, making it better for just dropping onto a bunny and using it.
5. Readme is much more descriptive (LED colors, how to config,.
6. Doesn't fail when the user does not have laZagne.exe on their bunny (there is no download link in the readme), and doesn't indicate it as a dependency in the readme for even partial operation (which is …

Addition of Exfiltration payload

---

payloads/extensions/debug.sh

- resolve sytax errors with variable declarations
- resolve misuse of command substition vs variable expansion
- inner functions were being called before being declared
- remove superfluous file existence checks

[FIX]  debug extension

---

payloads/extensions/mac_happy.sh

- fixes state leakage of `command` variable by removing it 
- remove unecessary use of forked processes/sub-commands
- combine input validation conditionals
- match the standard of existing extensions of exporting function
names as all caps
- bump version number

[FIX] mac_happy extension

---

payloads/extensions/waiteject.sh

This simple extension monitors the output of dmesg for the phrase "usb close backing file" which is what is logged when the USB storage is ejected by the OS. Tested on Linux and Windows hosts with Bash Bunny firmware version 1.5_298.
I needed this for a payload I am writing and decided to share it with the community before I finish the payload.
It may be a better idea to modify the existing WAIT function with WAIT SWITCH and WAIT EJECT. Thoughts?

New WAITEJECT Extension

---

payloads/library/recon/InfoGrabber/info.ps1

Removes all Variables created during the session. I noticed my version of PS was storing them between simulated attacks. so removing them entirely was my resolve.
Remove-Variable -Name computerPubIP,
computerIP,IsDHCPEnabled,Network,Networks, 
computerMAC,computerSystem,computerBIOS,computerOs,
computerCpu, computerMainboard,computerRamCapacity,
computerRam,driveType,Hdds,RDP,WLANProfileNames,WLANProfileName,
Output,WLANProfileObjects,WLANProfilePassword,WLANProfileObject,luser,
process,listener,listenerItem,process,service,software,drivers,videocard,
vault -ErrorAction SilentlyContinue -Force

Update for Info.ps1

---

payloads/library/prank/Startup-Message/payload.txt

You must add a delay after RUN WIN cmd or it won't always write on the cmd

Adding Delay to Prank/Startup-Message

---

payloads/library/general/ChromeOSDeployment/Readme.md
payloads/library/general/ChromeOSDeployment/payload.txt

This payload is for Chrome OS devices. This is for Version 70 and above.
The use case is to automatically go through the enterprise enrollment process and stop on the last page which lets the user add the unique asset name and asset ID of the device.

Chromeos Enrollment

---

payloads/library/credentials/Jackalope/payload.txt

Starting with Firmware 1.6 and the Metasploit tools package, RVM will no longer be needed.

Update Jackalope to remove references to RVM.

---

payloads/library/remote_access/RDP-Enable/README.md
payloads/library/remote_access/RDP-Enable/p.ps1
payloads/library/remote_access/RDP-Enable/payload.txt

Created a payload to enable RDP on Windows.
The payload will: 
Enable RDP.
Disable NLA.
Enable the administrator account and set a configurable password.
Create a backup admin account if required.
Log network information.
Log weather or not the attack succeeded.

Enable RDP, disable NLA, log network information.

---

payloads/library/credentials/LaZassword/README.md
payloads/library/credentials/LaZassword/bypass.ps1
payloads/library/credentials/LaZassword/lazassword.ps1
payloads/library/credentials/LaZassword/payload.txt

LaZassword is a payload that tricks Windows Defender, bypasses UAC and grabs passwords using LaZagne runned as admin. I already made a topic in the Hak5 forums and I've already made many improvements. This payload has many things that the [password grabber payload by jdebetaz](https://github.com/hak5/bashbunny-payloads/tree/master/payloads/library/credentials/PasswordGrabber) doesn't has, I think it's worth it to publish it to the official hak5 bashbunny-payload repository. It is also on [my github](https://github.com/githubkuyaya/LaZassword) of course. I would love to see it published!
Regards, kuyaya

Add LaZassword payload

---

payloads/library/credentials/Jackalope/readme.md

Change configuration description in jacklope payload readme telling users that jackalope is dependent on metasploit framework being installed

Jackalope: Update README to show Metasploit dependency.

---

payloads/library/phishing/Powershell_Local_DNS_Poisoning/README.md
payloads/library/phishing/Powershell_Local_DNS_Poisoning/payload.txt

Appends a domain and IP to the hosts file to poison the local DNS. Similar to github.com/hak5/bashbunny-payloads/tree/master/payloads/library/phishing/Local_DNS_Poisoning but uses powershell commands rather than cmd. On Windows 10 the old payload does not work as the commands used are deprecated (set, %variable%). There are also multiple spelling errors in the original payload, no comments are present, and it is not exactly clear what the user must change to use the payload.

Windows Powershell Local DNS Poisoning payload

---

payloads/library/exfiltration/keecopy/README.md
payloads/library/exfiltration/keecopy/payload.txt

This is an all-in-one script that utilizes keystroke automation to export an unencrypted copy of an unlocked KeePass database. 
The export will be saved in KeePass XML format on the Bash Bunny's storage partition under `loot/KPDB-YYYYmmdd-kkMMSS.xml` with the latter two portions of the filename being the date and time at which the export was performed.

New Payload: KeeCopy

---

payloads/library/credentials/win_sslkeylog/README.md
payloads/library/credentials/win_sslkeylog/payload.ps1
payloads/library/credentials/win_sslkeylog/payload.txt

Captures the client network session.
Captures the client side session keys.
1) Partially avoids "PowerShell Script Block Logging".
2) Closing of all windows.
3) Hide "PowerShell" window.
4) Check if current process have "Administrator" privilege.
5) Sets the "SSLKEYLOGFILE" environment variable to store SSL session key information. 
6) Starts a "Network Tracing Session" with "ETW (Event Tracing for Windows)".
7) Writes the file system cache to disk (thanks to @dark_pyrro).
8) Safely eject (thanks to @Night (9o3)).

Add Win_SSLKeyLog

---

payloads/library/prank/UnifiedRickRoll/payload.txt

While comparison = and == are identical on bash (refer http://www.tldp.org/LDP/abs/html/comparison-ops.html ), double equals behave differently on zsh (refer https://unix.stackexchange.com/questions/255480/why-does-behave-differently-inside-in-zsh-and-bash ). Single = is also equally POSIX compliant.
Co-Authored-By: Minh Thien Nhat Nguyen <nhat286@users.noreply.github.com>

Fix for zsh

---

payloads/library/credentials/sshDump/payload.txt

sshDump is BashBunny payload which takes advantage of unencrypted ssh private keys stored in home directory and loots them.

created sshDump

---

payloads/library/phishing/fake-sudo/README.md
payloads/library/phishing/fake-sudo/payload.txt
payloads/library/phishing/fake-sudo/sudo-phishing.sh

1) Copies the "sudo" command spoofing program to the user's home directory.
2) Defines a new persistent "sudo" alias with the file "~/.bash_aliases".
3) When the user "sudoer" executes the command "sudo" in a terminal, the spoofing program :
- __By default__ retrieves the username and password and writes them to "/tmp/.sudo_password".
- __But__ this behavior can be changed in line 21 of the "sudo-phishing.sh" file.
4) The spoofing program deletes the "sudo" alias. Then it deletes itself.

Add "Fake sudo"

---

payloads/library/prank/Win_HID_BeAPest/payload.txt
payloads/library/prank/Win_HID_BeAPest/readme.md

Uses CLSID to open system dialogs to swap the left and right mouse button, change the region to Welsh and turn off system sounds.

New Payload - Be a pest

---

payloads/library/phishing/fake-ssh/README.md
payloads/library/phishing/fake-ssh/payload.txt
payloads/library/phishing/fake-ssh/ssh-phishing.sh

1) Copies the "ssh" command spoofing program to the user's home directory.
2) Defines a new persistent "ssh" alias with the file "~/.bash_aliases".
3) When the user executes the command "ssh" in a terminal, the spoofing program :
- __By default__ retrieves the username@address and password and writes them to "/tmp/.ssh_password".
- __But__ this behavior can be changed in line 20 of the "ssh-phishing.sh" file.

Add Fake SSH

---

docs/readme.txt
payloads/extensions/get.sh

Instead of hardcoding "BashBunny" or whatever new name the Bunny has, attackers can use a GET command.

Add GET BB_LABEL function and docs

---

payloads/library/remote_access/Windows-Payload-Injector/payload.txt

What the payload does:
1) Disables Tamper Protection in Windows Defender.
2) Disables UAC / Turns UAC off
3) Creates Payload Directory in C:/ Drive
4) Disables Real-Time Protection in Windows Defender.
5) Adds the Payload Directory as an exclusion in Windows Defender
6) Downloads Payload from Specified URI (Enter in Variable Below)
7) Runs Payload on System

Windows Payload Injector Script

---

payloads/library/recon/WiFi-Hash-Scraper/Get-Hashes.ps1
payloads/library/recon/WiFi-Hash-Scraper/payload.txt

Scrapes and saves all the known network / wifi hashes on the victims pc to the loot folder of the bash bunny

WiFi Hash Scraper

---

payloads/library/recon/MacFetch/README.md
payloads/library/recon/MacFetch/fetch.sh
payloads/library/recon/MacFetch/payload.txt

- Current User
- All Users
- Hostname
- WiFi Interface
- Current WiFi Connection State
- Preferred WiFi Networks (Perfect for WiFi Pineapple’s SSID pool)
- Known Bluetooth Devices
- Clipboard
- Public IP
- Open Network Ports
- Applications
- Applications Starting at System Boot/Login
- Software and Hardware Information
- Terminal History
- Login History
- Apple ID Information
- Ifconfig output

Add MacFetch

---

payloads/library/prank/TV-Menu-Trigger/README.md
payloads/library/prank/TV-Menu-Trigger/payload.txt

This payload opens the main menu of a TV repeatedly at a random interval (1-10 minutes) to confuse and annoy the user.

Add TV-Menu-Trigger

---

payloads/library/phishing/MacAlertPhisher/README.md
payloads/library/phishing/MacAlertPhisher/payload.txt
payloads/library/phishing/MacAlertPhisher/script.sh

Creates a customizable alert that prompts for the victim's credentials and shares them with you via Discord. Even after unplugging the Bash Bunny.

Add MacAlertPhisher

---

payloads/library/prank/SleepyMacRick/README.md
payloads/library/prank/SleepyMacRick/payload.txt
payloads/library/prank/SleepyMacRick/rick.sh

Installs a script that will listen for user activity in the background. When the user starts working on his machine, a „Rick Roll“ will be triggered.

Add SleepyMacRick
